import type { Outlet, MenuItem, Order, UserProfile } from './types';

export const outlets: Outlet[] = [
  {
    id: 'outlet-1',
    name: 'Medical Cafeteria',
    description: 'Serving healthy and delicious meals for everyone.',
    imageId: 'outlet-medical-cafeteria',
    isActive: true,
    baseDeliveryTime: 15,
  },
  {
    id: 'outlet-2',
    name: 'Bits & Bites',
    description: 'Quick snacks, sandwiches, and refreshing beverages.',
    imageId: 'outlet-bits-bites',
    isActive: true,
    baseDeliveryTime: 10,
  },
];

export const menuItems: MenuItem[] = [
  // Medical Cafeteria
  {
    id: 'item-1',
    outletId: 'outlet-1',
    name: 'Chole Bhature',
    description: 'Spicy chickpeas curry served with fluffy deep-fried bread.',
    priceInr: 120,
    imageId: 'item-chole-bhature',
    category: 'Main Course',
    isAvailable: true,
    averagePrepTime: 15,
  },
  {
    id: 'item-2',
    outletId: 'outlet-1',
    name: 'Masala Dosa',
    description: 'A thin pancake of rice batter, filled with spiced potatoes.',
    priceInr: 100,
    imageId: 'item-masala-dosa',
    category: 'Main Course',
    isAvailable: true,
    averagePrepTime: 12,
  },
  {
    id: 'item-3',
    outletId: 'outlet-1',
    name: 'Paneer Tikka',
    description: 'Cubes of paneer marinated in spices and grilled in a tandoor.',
    priceInr: 150,
    imageId: 'item-paneer-tikka',
    category: 'Starters',
    isAvailable: true,
    averagePrepTime: 18,
  },
  {
    id: 'item-4',
    outletId: 'outlet-1',
    name: 'Vegetable Biryani',
    description: 'Aromatic rice dish with mixed vegetables and spices.',
    priceInr: 180,
    imageId: 'item-veg-biryani',
    category: 'Main Course',
    isAvailable: true,
    averagePrepTime: 20,
  },
    {
    id: 'item-5',
    outletId: 'outlet-1',
    name: 'Samosa',
    description: 'Fried pastry with a savory filling of spiced potatoes and peas.',
    priceInr: 30,
    imageId: 'item-samosa',
    category: 'Starters',
    isAvailable: true,
    averagePrepTime: 8,
  },
  {
    id: 'item-6',
    outletId: 'outlet-1',
    name: 'Filter Coffee',
    description: 'South Indian style drip coffee.',
    priceInr: 40,
    imageId: 'item-filter-coffee',
    category: 'Beverages',
    isAvailable: true,
    averagePrepTime: 5,
  },
    {
    id: 'item-7',
    outletId: 'outlet-1',
    name: 'Fresh Lime Soda',
    description: 'A refreshing drink with lime juice and soda.',
    priceInr: 50,
    imageId: 'item-fresh-lime-soda',
    category: 'Beverages',
    isAvailable: true,
    averagePrepTime: 3,
  },

  // Bits & Bites
  {
    id: 'item-8',
    outletId: 'outlet-2',
    name: 'Club Sandwich',
    description: 'Triple-layered sandwich with veg fillings, served with fries.',
    priceInr: 160,
    imageId: 'item-club-sandwich',
    category: 'Snacks',
    isAvailable: true,
    averagePrepTime: 10,
  },
  {
    id: 'item-9',
    outletId: 'outlet-2',
    name: 'Veg Hakka Noodles',
    description: 'Stir-fried noodles with a variety of vegetables.',
    priceInr: 140,
    imageId: 'item-veg-hakka-noodles',
    category: 'Main Course',
    isAvailable: true,
    averagePrepTime: 15,
  },
  {
    id: 'item-10',
    outletId: 'outlet-2',
    name: 'Chilli Paneer',
    description: 'Spicy and tangy indo-chinese dish with paneer and bell peppers.',
    priceInr: 180,
    imageId: 'item-chilli-paneer',
    category: 'Main Course',
    isAvailable: false,
    averagePrepTime: 18,
  },
  {
    id: 'item-11',
    outletId: 'outlet-2',
    name: 'Coca-Cola',
    description: 'A can of chilled Coca-Cola.',
    priceInr: 40,
    imageId: 'item-coke',
    category: 'Beverages',
    isAvailable: true,
    averagePrepTime: 1,
  },
];

export const mockUserProfile: UserProfile = {
  id: 'user-charlie-789',
  name: 'Charlie',
  email: 'charlie@example.com',
  phone: '+919876543212',
  address: '321, Foodie Lane, Gourmet City, 110001',
  isProfileComplete: false,
};

export const orders: Order[] = [
  {
    id: 'order-1',
    orderNumber: 'DH-001',
    tokenNumber: 101,
    outletId: 'outlet-1',
    items: [
      { menuItem: menuItems[0], quantity: 1 },
      { menuItem: menuItems[5], quantity: 2 },
    ],
    totalAmountInr: 200,
    status: 'preparing',
    estimatedWaitTime: 15,
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    clientName: 'Alice',
    clientId: 'user-alice-123'
  },
  {
    id: 'order-2',
    orderNumber: 'DH-002',
    tokenNumber: 102,
    outletId: 'outlet-2',
    items: [{ menuItem: menuItems[7], quantity: 2 }],
    totalAmountInr: 320,
    status: 'ready',
    estimatedWaitTime: 10,
    createdAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    clientName: 'Bob',
    clientId: 'user-bob-456'
  },
  {
    id: 'order-3',
    orderNumber: 'DH-003',
    tokenNumber: 103,
    outletId: 'outlet-1',
    items: [{ menuItem: menuItems[3], quantity: 1 }],
    totalAmountInr: 180,
    status: 'completed',
    estimatedWaitTime: 20,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    clientName: 'Charlie',
    clientId: 'user-charlie-789'
  },
    {
    id: 'order-4',
    orderNumber: 'DH-004',
    tokenNumber: 104,
    outletId: 'outlet-1',
    items: [{ menuItem: menuItems[1], quantity: 1 }],
    totalAmountInr: 100,
    status: 'pending',
    estimatedWaitTime: 12,
    createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    clientName: 'Charlie',
    clientId: 'user-charlie-789'
  },
];
